---
# vars file for ado_iterations_teams
## Black-listed projects
ado_project_blacklist:
  - 813e4c75-f058-4f2c-8e5e-c1442268973c

# BEGIN ANSIBLE PROJECT IDS
ado_project_ids_list: 
 - AZ-400 Playground
# END ANSIBLE PROJECT IDS
