---
- include_tasks: list-projects.yml
  tags:
    - list_projects

- include_tasks: list-classification-nodes.yml
  tags:
    - list_classifications

- include_tasks: list-teams.yml
  tags:
    - list_teams

- include_tasks: edit-create-sprints.yml
  tags:
    - patch/post_sprints